const containerHome=document.querySelector(".container-Home")
const containerCategoryMovies = document.querySelector('.container-category-movies');
const containerCategoryMoviesAll=document.querySelector(".container-category")
const cointainerTitle=document.querySelector(".title-container-category")
const profileContainer = document.querySelector('.profileContainer')
const iconSearch= document.querySelector('.input-icon')
const inputSearch=document.querySelector('.input-search')
const main = document.querySelector('main') 